palette = "rose-pine"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'
[character]
success_symbol = '[](bold iris)'
error_symbol = '[](bold love)'
vimcmd_symbol = '[](bold iris)'
